-- Auditoria para modulo Biblioteca (MySQL)
-- Agrega columnas Creado_Por, Creado_El, Modificado_Por, Modificado_El
-- Creado_Por/Modificado_Por se manejan como VARCHAR para almacenar Nombre_Usuario
-- Requiere MySQL 8.0+ para ADD COLUMN IF NOT EXISTS

SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE Bib_Tipo_Material
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Autor
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Editorial
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Categoria
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Libro
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Libro_Autor
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Tesis
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Serial
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Ejemplar
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Usuario_Biblioteca
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Proveedor
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Presupuesto
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Orden_Compra
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Orden_Compra_Detalle
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Factura_Compra
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Cotizacion
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Sede
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Integracion
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Politica_Prestamo
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Prestamo
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Reserva
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Multa
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Auditoria_Circulacion
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Marc_Registro
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Marc_Campo
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Marc_Subcampo
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Autoridad
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Autoridad_Campo
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Autoridad_Subcampo
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Suscripcion
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Serial_Numero
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Serial_Recepcion
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Opac_Comentario
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Opac_Etiqueta
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Opac_Lista
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Opac_Lista_Item
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Opac_Historial_Busqueda
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Rol
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Permiso
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Rol_Permiso
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE Bib_Usuario_Rol
  ADD COLUMN IF NOT EXISTS Creado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Creado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS Modificado_Por VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS Modificado_El DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

SET FOREIGN_KEY_CHECKS = 1;
